[ids]
*

[main]
capslock = overload(capslock, esc)
esc = capslock
insert = print


[capslock:C]
j = left
k = down
i = up
l = right
p = compose
a = kp4
s = kp2
w = kp8
d = kp6
e = leftmouse
q = rightmouse
tab = numlock
- = brightnessdown
= = brightnessup
space =  play
9 = previoussong
0 = nextsong
7 = volumedown
8 = volumeup
1 = www
4 = f4
5 = f5
semicolon = wlan
' = bluetooth
